config/routes.rb
Shukin::Application.routes.draw do

  resources :enquiries do
    resources :quotes
  end

  match ':controller/:action.:format'

  get "sessions/new"

  get "product/new"

  resources :manufacturers
  resources :products
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories
  resources :sub_categories

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/products_page', :to => 'pages#products_page'
  match '/contact', :to => 'pages#contact'
  match '/admin', :to => 'pages#admin'

  root :to => "pages#home"

end

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
  Our customers have been coming to us for generations because they trust
  us and know they can get quality produce at the best value time and
  time again. We are proud to have formed relationships and personally
  know a lot of our customers.
</p>
<p>
  From our base in Sheffield, we supply a range of businesses, from bakers, cafes, restaurants, sandwich
  shops to individuals wishing to purchase some specialised quality wholesale ingredients
  at great value prices.
</p>
<p>
  Our experienced team can deliver your order to your door. Please
  <%= link_to "contact us", contact_path %> to find out more about what we can offer you.
</p>

<h2>Our history</h2>
<p>
  We've been around since 1873 and have built our business on service, reliability,
  quality, trust and great value.
</p>
<p>
  <%= photo_old %>
</p>

<h2>Our products</h2>
<p>
  We stock many products including a large range of bakery, confectionary and cake decorating
  supplies, please see our <a href="products_page">products page</a> to view a selection of our
  produce.
</p>
<p>
  We've built such a good relationship with our suppliers that we are able to secure products at great rates,
  which we can pass on to you. If there is anything you are looking for which you can't find on our site,
  please contact us and we will endeavor to get hold of it for you or find an alternative ingredient/product.
</p>

app/views/pages/admin.html.erb
<%= render "sessions/sign_in_out" %>

<% if  signed_in? %>
<table>
  <tr>
    <td>
      <%= link_to 'Manufacturers', manufacturers_path %> |
    </td>
    <td>
      <%= link_to 'Categories', categories_path %> |
    </td>
    <td>
      <%= link_to 'Sub-categories', sub_categories_path %> |
    </td>
    <td>
      <%= link_to 'Products', products_path %>
    </td>

  </tr>
</table>
<% end %>

app/views/pages/contact.html.erb
<h1>Contact Details</h1>
<p>
  Phone: +44 (0)114 2551397
</p>
<p>
  Fax: +44 (0) 1949 81409
</p>
<p>
  Email: enquiries@shukin.co.uk
</p>
<p>
  You can find us here:<br />
  25 Thirlwell Rd, Sheffield, South Yorkshire, S8 9TE, UK
</p>
<p>
  <%= render 'layouts/map' %>
</p>

app/views/pages/home.html.erb
<div id="home_main" style="height: 488px; width: 688px; background-image:url('/images/main_pic_3.1.jpg')">
<div style="background-image: url('/images/shade2.png'); width: 550px; height: 160px; left: 0px; position: relative; top: 0px;">
  <div style="padding:15px; font-weight: bold; color: #fffaf6; font-size: 36px;">
  Supplying local businesses <br/>
  with quality wholesale food<br/>
  produce since 1873.
  </div>
</div>
<div style="background-image: url('/images/shade3.png'); position: relative; top: 67px; width: 485px; left: 203px; height: 115px;">
  <div style="padding:15px; font-weight: bold; color: #ffdfcb; font-size: 36px; text-align: right">
  We deliver direct to your<br/>
  door 7 days a week.
  </div>
</div>
<div style="background-image: url('/images/shade3.png'); width: 606px; position: relative; top: 89px; height: 109px; left: 0px;">
  <div style="padding:15px; font-weight: bold; color: #ffdfcb; font-size: 36px;">
    <a href="contact" style="color: #FFDFCB;">Get in touch to find out more<br/>
   about our products and services.</a>
  </div>
</div>
</div>

app/views/pages/products_page.html.erb
<h1>Our Products</h1>
<p>
  We stock products from quality manufactures including, Renshaw, Bakemark,
  Culpitt, Puratos, Macphie, Bradshaws, Morley, Britannia, Ingram,
  Surafti, Tate & Lyle and many more.
</p>
<p>
  <div>
  Find the products your looking for here:
  </div>
  <p>
  <%= render 'shared/product_search' %>
  <i>&nbsp;OR...</i> Click on the categories below to browse our products.
  </p>


  <%= render 'shared/sup_cat_browse' %>
 
  <%= render 'products/browse' %>
</p>