config/routes.rb
Shukin::Application.routes.draw do

  resources :enquiries do
    resources :quotes
  end

  match ':controller/:action.:format'

  get "sessions/new"

  get "product/new"

  resources :manufacturers
  resources :products
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories
  resources :sub_categories

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/products_page', :to => 'pages#products_page'
  match '/contact', :to => 'pages#contact'
  match '/admin', :to => 'pages#admin'

  root :to => "pages#home"

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

  attr_accessible :name, :category_id

  belongs_to :category
  has_many :products
  
  validates :name, :presence => true, :length => { :maximum => 140 }
  validates :category_id, :presence => true

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_filter :authenticate
  # GET /sub_categories
  # GET /sub_categories.xml
  def index
    @sub_categories = SubCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sub_categories }
    end
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.xml
  def show
    @sub_category = SubCategory.find(params[:id])
    @category = Category.find(@sub_category.category_id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/new
  # GET /sub_categories/new.xml
  def new
    @sub_category = SubCategory.new

    # fetches all the categories, ordered by their name
    @categories = Category.order(:name)
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
    @categories = Category.order(:name)
  end

  # POST /sub_categories
  # POST /sub_categories.xml
  def create
    @sub_category = SubCategory.new(params[:sub_category])
    @categories = Category.order(:name)
    
    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully created.') }
        format.xml  { render :xml => @sub_category, :status => :created, :location => @sub_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categories/1
  # PUT /sub_categories/1.xml
  def update
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      if @sub_category.update_attributes(params[:sub_category])
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.xml
  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to(sub_categories_url) }
      format.xml  { head :ok }
    end
  end

  private

    def authenticate
      deny_access unless signed_in?
    end

end

app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, @categories, :id, :name, {:prompt => true}, {"style" => "width:200px"} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/_sub_categories.html.erb
<tr>
  <td class="sub_categories">
    <span class="name"><%= sub_category.name %></span>
  </td>
</tr>

app/views/sub_categories/_sub_category.html.erb
<tr>
  <td class="sub_category">
    <span class="content"><%= sub_category.name %></span>
  </td>
  <td>
    <%= link_to "delete", sub_category, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => sub_category.name %>
  </td>
</tr>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub category</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<h1>Listing sub categories</h1>

<table>
  <tr>
    <th>Parent Category</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sub_categories.each do |sub_category| %>
  <tr>
    <td><%= sub_category.category.name%></td>
    <td><%= sub_category.name %></td>
    <td><%= link_to 'Show', sub_category %></td>
    <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
    <td><%= button_to "delete", sub_category, :method => :delete, :confirm => "Are you sure?", :class => :destroy %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub category</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p>
  <b>Category Name:</b>
  <%= @category.name %>
</p>
<p>
  <b>Sub Category Name:</b>
  <%= @sub_category.name %>
</p>


<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>