config/routes.rb
Shukin::Application.routes.draw do

  resources :enquiries do
    resources :quotes
  end

  match ':controller/:action.:format'

  get "sessions/new"

  get "product/new"

  resources :manufacturers
  resources :products
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories
  resources :sub_categories

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/products_page', :to => 'pages#products_page'
  match '/contact', :to => 'pages#contact'
  match '/admin', :to => 'pages#admin'

  root :to => "pages#home"

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessible :name

  has_many :sub_categories, :dependent => :destroy
  has_many :products

  validates :name, :presence => true, :length => { :maximum => 140 }


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
    @sub_categories = @category.sub_categories

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

#    @category.sub_categories << SubCategory.new(:name => @category.name)
     @sub_category = @category.sub_categories.build(:name=>@category.name, :category_id=>Category.last.id)

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end

  private

    def authenticate
      deny_access unless signed_in?
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_browse.html.erb
<div class="cat_nav">
  <ul id="<%= @current_cat.blank? ? "every" : @current_cat.id %>_cat">
    <% @categories.each do |category| %>
      <li <%= @current_cat == category ? "class='selected'":""  %> ><%= link_to category.name, products_page_path(:id => category.id), :id => category.id %></li>
    <% end %>

  </ul>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= button_to "delete", category, :method => :delete, :confirm => "Are you sure?", :class => :destroy %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<% unless @category.sub_categories.empty? %>
  <table class="sub_categories" summary="Category sub categories">
    <%= render @sub_categories %>
  </table>
<% else %>
   <p>
     This category has no sub-categories.
   </p>
<% end %>


<%= link_to 'New SubCategory', new_sub_category_path %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>