config/routes.rb
Shukin::Application.routes.draw do

  resources :enquiries do
    resources :quotes
  end

  match ':controller/:action.:format'

  get "sessions/new"

  get "product/new"

  resources :manufacturers
  resources :products
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories
  resources :sub_categories

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/products_page', :to => 'pages#products_page'
  match '/contact', :to => 'pages#contact'
  match '/admin', :to => 'pages#admin'

  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<div id="copy_footer">
  © Copyright 2012 S.Hukin ltd. All rights reserved.
  <div id="eightacross_footer">
    <%= link_to eight_across_digital_logo, "http://www.eightacross.com" %>
  </div> 
</div>

app/views/layouts/_header.html.erb
<div class="logo">
  <%= link_to logo, root_path %>
</div>
<div class="nav">
  <ul id="<%= @current_page %>_page"> 
    <li><%= link_to "Contact", contact_path, :id => "contact_nav" %></li>
    <li><%= link_to "Products", products_page_path, :id => "products_page_nav" %></li>
    <li><%= link_to "About", about_path, :id => "about_nav" %></li>
    <li><%= link_to "Home", root_path, :id => "home_nav" %></li>
  </ul>
</div>

app/views/layouts/_info_right.html.erb
<h2 class="info_head">
  Products<br/>
  <%= render 'shared/product_search' %>
</h2>
<ul class="info_list">
  <li><%= link_to bakers_hat, products_page_path(:id => $baking_categories, :sup_cat_name => "baking") %> <%= link_to "Baking", products_page_path(:id => $baking_categories, :sup_cat_name => "baking") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $dairy_categories, :sup_cat_name => "dairy") %> <%= link_to "Dairy", products_page_path(:id => $dairy_categories, :sup_cat_name => "dairy") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $decorating_categories, :sup_cat_name => "decorating") %> <%= link_to "Cake Decorations", products_page_path(:id => $decorating_categories, :sup_cat_name => "decorating") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $fats_oils_categoies, :sup_cat_name => "fats & oils") %> <%= link_to "Bakery Fats & Oils", products_page_path(:id => $fats_oils_categoies, :sup_cat_name => "fats & oils") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $fruit_nuts_categoies, :sup_cat_name => "fruit & nuts") %> <%= link_to "Dried Fruits & Nuts", products_page_path(:id => $fruit_nuts_categoies, :sup_cat_name => "fruit & nuts") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $sweet_categoies, :sup_cat_name => "sweet") %> <%= link_to "Sweet", products_page_path(:id => $sweet_categoies, :sup_cat_name => "sweet") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $savoury_categoies, :sup_cat_name => "savoury") %> <%= link_to "Savoury", products_page_path(:id => $savoury_categoies, :sup_cat_name => "savoury") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $non_edible_categoies, :sup_cat_name => "non edible") %> <%= link_to "Non Edible", products_page_path(:id => $non_edible_categoies, :sup_cat_name => "non edible") %></li>
  <li><%= link_to bakers_hat, products_page_path(:id => $other_consumables_categoies, :sup_cat_name => "other consumables") %> <%= link_to raw("Other Consumables - <div style='padding-left:25px; font-size:12px'>i.e. packaging, bags, foils, cake boards etc.</div>"), products_page_path(:id => $other_consumables_categoies, :sup_cat_name => "other consumables") %></li>
  
</ul>

app/views/layouts/_info_right_bottom.html.erb
<h2 class="info_head">
  News
</h2>
<ul class="info_list">
  <li><%= link_to "Checkout the latest product range", products_page_path %></li>
  <li>Get a quote now!</li>
</ul>

app/views/layouts/_map.html.erb
<iframe width="650" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;msa=0&amp;msid=208538710394604596752.00049dc86c84c626bafbd&amp;ll=53.362641,-1.472168&amp;spn=0.071707,0.188828&amp;z=12&amp;output=embed"></iframe><br /><small>View <a href="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;msa=0&amp;msid=208538710394604596752.00049dc86c84c626bafbd&amp;ll=53.362641,-1.472168&amp;spn=0.071707,0.188828&amp;z=12&amp;source=embed" style="color:#0000FF;text-align:left">S Hukin ltd</a> in a larger map</small>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="szU2Cb3vmkzHCBSfOcqxKc63pCH_4ZZq6nmiOQJdNSw" />
    <title><%= title %></title>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= render 'layouts/stylesheets' %>
    <%= yield(:head) %>
    <!-- SCRIPT FOR GOOGLE ANALYTICS -->
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-9041635-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    <meta property="og:type" content="food"/>
    <meta property="og:title" content="S.Hukin ltd - Sheffield, UK. Wholesale foods & bakers supplies."/>
    <meta property="og:image" content="http://www.shukin.co.uk/images/s.hukin_fb_v1.0.jpg"/>
    <meta property="og:url" content="http://shukin.co.uk"/>
    <meta property="og:site_name" content="S.Hukin ltd"/>

  </head>
  <body>
    <!-- BACKGROUND FOR EXPANDABLE HEADER -->
    <div class="header">
      <div class="container_head">
        <div style="background-image: url(&quot;/images/tear_left.png&quot;);
             background-repeat: repeat-y; top: -18px; position: relative; width: 5px;
             left: -40px; margin-bottom: -879px; height: 879px; "></div>
        <div style="background-image: url(&quot;/images/tear_right.png&quot;);
             background-repeat: repeat-y; top: -18px; position: relative; width: 10px;
             left: 933px; margin-bottom: -879px; height: 879px;"></div>
        <%= render 'layouts/header' %>

      </div>
    </div>
    <div class="main">
      <!-- CENTER CONTENT -->
      <div class="container_main" id="container_main">
        <div class="container_sub_right">
          <%= customer_services %>
        </div>
        <div class="container_sub_right">
          <%= render 'layouts/info_right' %>
        </div>
        <div class="container_sub_left">
          <section>
            <% flash.each do |key, value| %>
              <div class="flash <%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
          </section>
        </div>
      </div>
    </div>
    <!--CLEAR FOOTER TO PREVENT BUNCHING-->
    <div class="clear"></div>
    <div class="footer">
      <div class="container_footer">
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>